// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (non-pooled) connection — required for DDL during migrations.
    // Runtime queries use DATABASE_URL (pgbouncer) via the adapter in src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
