// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Conexão que as migrations usam para aplicar DDL.
    //
    // `DIRECT_URL` existe por causa do Supabase, onde `DATABASE_URL` aponta
    // para o pgbouncer e não serve para DDL. Em produção o Postgres roda ao
    // lado da aplicação, sem pooler, e só existe `DATABASE_URL` — daí a
    // alternativa. Sem ela, o `migrate deploy` sobe sem saber onde está o banco
    // e falha com exit 1, antes de qualquer mensagem útil.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
